// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsFoundationModelsApi(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashFoundationModelsApi(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsFoundationModelsApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsFoundationModelsApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsFoundationModelsApi(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsFoundationModelsApi(lhsKey, rhsKey) {
          if deepEqualsFoundationModelsApi(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsFoundationModelsApi(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashFoundationModelsApi(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashFoundationModelsApi(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashFoundationModelsApi(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashFoundationModelsApi(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashFoundationModelsApi(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashFoundationModelsApi(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Generated class from Pigeon that represents data sent in messages.
struct NativeGenerateRequest: Hashable {
  var messages: [NativeMessage]
  var systemInstruction: String? = nil
  var configJson: String? = nil
  var toolsJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeGenerateRequest? {
    let messages = pigeonVar_list[0] as! [NativeMessage]
    let systemInstruction: String? = nilOrValue(pigeonVar_list[1])
    let configJson: String? = nilOrValue(pigeonVar_list[2])
    let toolsJson: String? = nilOrValue(pigeonVar_list[3])

    return NativeGenerateRequest(
      messages: messages,
      systemInstruction: systemInstruction,
      configJson: configJson,
      toolsJson: toolsJson
    )
  }
  func toList() -> [Any?] {
    return [
      messages,
      systemInstruction,
      configJson,
      toolsJson,
    ]
  }
  static func == (lhs: NativeGenerateRequest, rhs: NativeGenerateRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsFoundationModelsApi(lhs.messages, rhs.messages) && deepEqualsFoundationModelsApi(lhs.systemInstruction, rhs.systemInstruction) && deepEqualsFoundationModelsApi(lhs.configJson, rhs.configJson) && deepEqualsFoundationModelsApi(lhs.toolsJson, rhs.toolsJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeGenerateRequest")
    deepHashFoundationModelsApi(value: messages, hasher: &hasher)
    deepHashFoundationModelsApi(value: systemInstruction, hasher: &hasher)
    deepHashFoundationModelsApi(value: configJson, hasher: &hasher)
    deepHashFoundationModelsApi(value: toolsJson, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeMessage: Hashable {
  var role: String
  var parts: [NativePart]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeMessage? {
    let role = pigeonVar_list[0] as! String
    let parts = pigeonVar_list[1] as! [NativePart]

    return NativeMessage(
      role: role,
      parts: parts
    )
  }
  func toList() -> [Any?] {
    return [
      role,
      parts,
    ]
  }
  static func == (lhs: NativeMessage, rhs: NativeMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsFoundationModelsApi(lhs.role, rhs.role) && deepEqualsFoundationModelsApi(lhs.parts, rhs.parts)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeMessage")
    deepHashFoundationModelsApi(value: role, hasher: &hasher)
    deepHashFoundationModelsApi(value: parts, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativePart: Hashable {
  var text: String? = nil
  var toolRequestJson: String? = nil
  var toolResponseJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativePart? {
    let text: String? = nilOrValue(pigeonVar_list[0])
    let toolRequestJson: String? = nilOrValue(pigeonVar_list[1])
    let toolResponseJson: String? = nilOrValue(pigeonVar_list[2])

    return NativePart(
      text: text,
      toolRequestJson: toolRequestJson,
      toolResponseJson: toolResponseJson
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      toolRequestJson,
      toolResponseJson,
    ]
  }
  static func == (lhs: NativePart, rhs: NativePart) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsFoundationModelsApi(lhs.text, rhs.text) && deepEqualsFoundationModelsApi(lhs.toolRequestJson, rhs.toolRequestJson) && deepEqualsFoundationModelsApi(lhs.toolResponseJson, rhs.toolResponseJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativePart")
    deepHashFoundationModelsApi(value: text, hasher: &hasher)
    deepHashFoundationModelsApi(value: toolRequestJson, hasher: &hasher)
    deepHashFoundationModelsApi(value: toolResponseJson, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeGenerateResponse: Hashable {
  var parts: [NativePart]
  var finishReason: String? = nil
  var errorCode: String? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeGenerateResponse? {
    let parts = pigeonVar_list[0] as! [NativePart]
    let finishReason: String? = nilOrValue(pigeonVar_list[1])
    let errorCode: String? = nilOrValue(pigeonVar_list[2])
    let errorMessage: String? = nilOrValue(pigeonVar_list[3])

    return NativeGenerateResponse(
      parts: parts,
      finishReason: finishReason,
      errorCode: errorCode,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      parts,
      finishReason,
      errorCode,
      errorMessage,
    ]
  }
  static func == (lhs: NativeGenerateResponse, rhs: NativeGenerateResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsFoundationModelsApi(lhs.parts, rhs.parts) && deepEqualsFoundationModelsApi(lhs.finishReason, rhs.finishReason) && deepEqualsFoundationModelsApi(lhs.errorCode, rhs.errorCode) && deepEqualsFoundationModelsApi(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeGenerateResponse")
    deepHashFoundationModelsApi(value: parts, hasher: &hasher)
    deepHashFoundationModelsApi(value: finishReason, hasher: &hasher)
    deepHashFoundationModelsApi(value: errorCode, hasher: &hasher)
    deepHashFoundationModelsApi(value: errorMessage, hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct NativeGenerateStreamEvent: Hashable {
  var requestId: String? = nil
  var parts: [NativePart]? = nil
  var done: Bool? = nil
  var response: NativeGenerateResponse? = nil
  var errorCode: String? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeGenerateStreamEvent? {
    let requestId: String? = nilOrValue(pigeonVar_list[0])
    let parts: [NativePart]? = nilOrValue(pigeonVar_list[1])
    let done: Bool? = nilOrValue(pigeonVar_list[2])
    let response: NativeGenerateResponse? = nilOrValue(pigeonVar_list[3])
    let errorCode: String? = nilOrValue(pigeonVar_list[4])
    let errorMessage: String? = nilOrValue(pigeonVar_list[5])

    return NativeGenerateStreamEvent(
      requestId: requestId,
      parts: parts,
      done: done,
      response: response,
      errorCode: errorCode,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      parts,
      done,
      response,
      errorCode,
      errorMessage,
    ]
  }
  static func == (lhs: NativeGenerateStreamEvent, rhs: NativeGenerateStreamEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsFoundationModelsApi(lhs.requestId, rhs.requestId) && deepEqualsFoundationModelsApi(lhs.parts, rhs.parts) && deepEqualsFoundationModelsApi(lhs.done, rhs.done) && deepEqualsFoundationModelsApi(lhs.response, rhs.response) && deepEqualsFoundationModelsApi(lhs.errorCode, rhs.errorCode) && deepEqualsFoundationModelsApi(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeGenerateStreamEvent")
    deepHashFoundationModelsApi(value: requestId, hasher: &hasher)
    deepHashFoundationModelsApi(value: parts, hasher: &hasher)
    deepHashFoundationModelsApi(value: done, hasher: &hasher)
    deepHashFoundationModelsApi(value: response, hasher: &hasher)
    deepHashFoundationModelsApi(value: errorCode, hasher: &hasher)
    deepHashFoundationModelsApi(value: errorMessage, hasher: &hasher)
  }
}

private class FoundationModelsApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeGenerateRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return NativeMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return NativePart.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeGenerateResponse.fromList(self.readValue() as! [Any?])
    case 133:
      return NativeGenerateStreamEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FoundationModelsApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeGenerateRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NativeMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativePart {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeGenerateResponse {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NativeGenerateStreamEvent {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FoundationModelsApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FoundationModelsApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FoundationModelsApiPigeonCodecWriter(data: data)
  }
}

class FoundationModelsApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FoundationModelsApiPigeonCodec(readerWriter: FoundationModelsApiPigeonCodecReaderWriter())
}

var foundationModelsApiPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: FoundationModelsApiPigeonCodecReaderWriter());


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FoundationModelsHostApi {
  func generate(request: NativeGenerateRequest, completion: @escaping (Result<NativeGenerateResponse, Error>) -> Void)
  func startGenerateStream(request: NativeGenerateRequest, completion: @escaping (Result<String, Error>) -> Void)
  func cancelGenerateStream(requestId: String) throws
  func isAvailable(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FoundationModelsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FoundationModelsApiPigeonCodec.shared }
  /// Sets up an instance of `FoundationModelsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FoundationModelsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let generateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.genkit_foundation_models.FoundationModelsHostApi.generate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! NativeGenerateRequest
        api.generate(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateChannel.setMessageHandler(nil)
    }
    let startGenerateStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.genkit_foundation_models.FoundationModelsHostApi.startGenerateStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startGenerateStreamChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! NativeGenerateRequest
        api.startGenerateStream(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startGenerateStreamChannel.setMessageHandler(nil)
    }
    let cancelGenerateStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.genkit_foundation_models.FoundationModelsHostApi.cancelGenerateStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelGenerateStreamChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        do {
          try api.cancelGenerateStream(requestId: requestIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelGenerateStreamChannel.setMessageHandler(nil)
    }
    let isAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.genkit_foundation_models.FoundationModelsHostApi.isAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isAvailableChannel.setMessageHandler { _, reply in
        api.isAvailable { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isAvailableChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

class StreamEventsStreamHandler: PigeonEventChannelWrapper<NativeGenerateStreamEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: StreamEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.genkit_foundation_models.FoundationModelsStreamApi.streamEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<NativeGenerateStreamEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: foundationModelsApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
