// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum FoundationModelsApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Native generation request sent from Dart to Swift.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeGenerateRequest: Hashable, CustomStringConvertible {
  /// Ordered conversation messages to send to the native model.
  var messages: [NativeMessage]
  /// Optional system instruction used to initialize the native session.
  var systemInstruction: String? = nil
  /// JSON-encoded generation config such as temperature or token limit.
  var configJson: String? = nil
  /// JSON-encoded tool declarations for native tool capture.
  var toolsJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeGenerateRequest? {
    let messages = pigeonVar_list[0] as! [NativeMessage]
    let systemInstruction: String? = nilOrValue(pigeonVar_list[1])
    let configJson: String? = nilOrValue(pigeonVar_list[2])
    let toolsJson: String? = nilOrValue(pigeonVar_list[3])

    return NativeGenerateRequest(
      messages: messages,
      systemInstruction: systemInstruction,
      configJson: configJson,
      toolsJson: toolsJson
    )
  }
  func toList() -> [Any?] {
    return [
      messages,
      systemInstruction,
      configJson,
      toolsJson,
    ]
  }
  static func == (lhs: NativeGenerateRequest, rhs: NativeGenerateRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FoundationModelsApiPigeonInternal.deepEquals(lhs.messages, rhs.messages) && FoundationModelsApiPigeonInternal.deepEquals(lhs.systemInstruction, rhs.systemInstruction) && FoundationModelsApiPigeonInternal.deepEquals(lhs.configJson, rhs.configJson) && FoundationModelsApiPigeonInternal.deepEquals(lhs.toolsJson, rhs.toolsJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeGenerateRequest")
    FoundationModelsApiPigeonInternal.deepHash(value: messages, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: systemInstruction, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: configJson, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: toolsJson, hasher: &hasher)
  }

  public var description: String {
    return "NativeGenerateRequest(messages: \(String(describing: messages)), systemInstruction: \(String(describing: systemInstruction)), configJson: \(String(describing: configJson)), toolsJson: \(String(describing: toolsJson)))"
  }
}

/// One conversation message for the native Foundation Models bridge.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeMessage: Hashable, CustomStringConvertible {
  /// Genkit role value such as `user`, `model`, or `tool`.
  var role: String
  /// Ordered message parts.
  var parts: [NativePart]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeMessage? {
    let role = pigeonVar_list[0] as! String
    let parts = pigeonVar_list[1] as! [NativePart]

    return NativeMessage(
      role: role,
      parts: parts
    )
  }
  func toList() -> [Any?] {
    return [
      role,
      parts,
    ]
  }
  static func == (lhs: NativeMessage, rhs: NativeMessage) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FoundationModelsApiPigeonInternal.deepEquals(lhs.role, rhs.role) && FoundationModelsApiPigeonInternal.deepEquals(lhs.parts, rhs.parts)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeMessage")
    FoundationModelsApiPigeonInternal.deepHash(value: role, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: parts, hasher: &hasher)
  }

  public var description: String {
    return "NativeMessage(role: \(String(describing: role)), parts: \(String(describing: parts)))"
  }
}

/// One native message or response part.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativePart: Hashable, CustomStringConvertible {
  /// Plain text content.
  var text: String? = nil
  /// JSON-encoded Genkit tool request.
  var toolRequestJson: String? = nil
  /// JSON-encoded Genkit tool response.
  var toolResponseJson: String? = nil
  /// Native reasoning/debug text. Never assistant-visible response text.
  var reasoningText: String? = nil
  /// JSON-encoded metadata for this part.
  var metadataJson: String? = nil
  /// JSON-encoded custom data for this part.
  var customJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativePart? {
    let text: String? = nilOrValue(pigeonVar_list[0])
    let toolRequestJson: String? = nilOrValue(pigeonVar_list[1])
    let toolResponseJson: String? = nilOrValue(pigeonVar_list[2])
    let reasoningText: String? = nilOrValue(pigeonVar_list[3])
    let metadataJson: String? = nilOrValue(pigeonVar_list[4])
    let customJson: String? = nilOrValue(pigeonVar_list[5])

    return NativePart(
      text: text,
      toolRequestJson: toolRequestJson,
      toolResponseJson: toolResponseJson,
      reasoningText: reasoningText,
      metadataJson: metadataJson,
      customJson: customJson
    )
  }
  func toList() -> [Any?] {
    return [
      text,
      toolRequestJson,
      toolResponseJson,
      reasoningText,
      metadataJson,
      customJson,
    ]
  }
  static func == (lhs: NativePart, rhs: NativePart) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FoundationModelsApiPigeonInternal.deepEquals(lhs.text, rhs.text) && FoundationModelsApiPigeonInternal.deepEquals(lhs.toolRequestJson, rhs.toolRequestJson) && FoundationModelsApiPigeonInternal.deepEquals(lhs.toolResponseJson, rhs.toolResponseJson) && FoundationModelsApiPigeonInternal.deepEquals(lhs.reasoningText, rhs.reasoningText) && FoundationModelsApiPigeonInternal.deepEquals(lhs.metadataJson, rhs.metadataJson) && FoundationModelsApiPigeonInternal.deepEquals(lhs.customJson, rhs.customJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativePart")
    FoundationModelsApiPigeonInternal.deepHash(value: text, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: toolRequestJson, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: toolResponseJson, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: reasoningText, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: metadataJson, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: customJson, hasher: &hasher)
  }

  public var description: String {
    return "NativePart(text: \(String(describing: text)), toolRequestJson: \(String(describing: toolRequestJson)), toolResponseJson: \(String(describing: toolResponseJson)), reasoningText: \(String(describing: reasoningText)), metadataJson: \(String(describing: metadataJson)), customJson: \(String(describing: customJson)))"
  }
}

/// Complete native generation response.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeGenerateResponse: Hashable, CustomStringConvertible {
  /// Response parts returned by the native model bridge.
  var parts: [NativePart]
  /// Optional native finish reason.
  var finishReason: String? = nil
  /// Optional native error code.
  var errorCode: String? = nil
  /// Optional native error message.
  var errorMessage: String? = nil
  /// JSON-encoded response custom metadata.
  var customJson: String? = nil
  /// JSON-encoded raw native response/debug metadata.
  var rawJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeGenerateResponse? {
    let parts = pigeonVar_list[0] as! [NativePart]
    let finishReason: String? = nilOrValue(pigeonVar_list[1])
    let errorCode: String? = nilOrValue(pigeonVar_list[2])
    let errorMessage: String? = nilOrValue(pigeonVar_list[3])
    let customJson: String? = nilOrValue(pigeonVar_list[4])
    let rawJson: String? = nilOrValue(pigeonVar_list[5])

    return NativeGenerateResponse(
      parts: parts,
      finishReason: finishReason,
      errorCode: errorCode,
      errorMessage: errorMessage,
      customJson: customJson,
      rawJson: rawJson
    )
  }
  func toList() -> [Any?] {
    return [
      parts,
      finishReason,
      errorCode,
      errorMessage,
      customJson,
      rawJson,
    ]
  }
  static func == (lhs: NativeGenerateResponse, rhs: NativeGenerateResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FoundationModelsApiPigeonInternal.deepEquals(lhs.parts, rhs.parts) && FoundationModelsApiPigeonInternal.deepEquals(lhs.finishReason, rhs.finishReason) && FoundationModelsApiPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode) && FoundationModelsApiPigeonInternal.deepEquals(lhs.errorMessage, rhs.errorMessage) && FoundationModelsApiPigeonInternal.deepEquals(lhs.customJson, rhs.customJson) && FoundationModelsApiPigeonInternal.deepEquals(lhs.rawJson, rhs.rawJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeGenerateResponse")
    FoundationModelsApiPigeonInternal.deepHash(value: parts, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: finishReason, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: errorMessage, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: customJson, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: rawJson, hasher: &hasher)
  }

  public var description: String {
    return "NativeGenerateResponse(parts: \(String(describing: parts)), finishReason: \(String(describing: finishReason)), errorCode: \(String(describing: errorCode)), errorMessage: \(String(describing: errorMessage)), customJson: \(String(describing: customJson)), rawJson: \(String(describing: rawJson)))"
  }
}

/// Event emitted while a native generation request is streaming.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NativeGenerateStreamEvent: Hashable, CustomStringConvertible {
  /// Native stream request id used to filter shared event-channel events.
  var requestId: String? = nil
  /// Incremental response parts.
  var parts: [NativePart]? = nil
  /// Whether this event closes the stream.
  var done: Bool? = nil
  /// Final response included on the closing event.
  var response: NativeGenerateResponse? = nil
  /// Optional native stream error code.
  var errorCode: String? = nil
  /// Optional native stream error message.
  var errorMessage: String? = nil
  /// JSON-encoded stream chunk custom metadata.
  var customJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeGenerateStreamEvent? {
    let requestId: String? = nilOrValue(pigeonVar_list[0])
    let parts: [NativePart]? = nilOrValue(pigeonVar_list[1])
    let done: Bool? = nilOrValue(pigeonVar_list[2])
    let response: NativeGenerateResponse? = nilOrValue(pigeonVar_list[3])
    let errorCode: String? = nilOrValue(pigeonVar_list[4])
    let errorMessage: String? = nilOrValue(pigeonVar_list[5])
    let customJson: String? = nilOrValue(pigeonVar_list[6])

    return NativeGenerateStreamEvent(
      requestId: requestId,
      parts: parts,
      done: done,
      response: response,
      errorCode: errorCode,
      errorMessage: errorMessage,
      customJson: customJson
    )
  }
  func toList() -> [Any?] {
    return [
      requestId,
      parts,
      done,
      response,
      errorCode,
      errorMessage,
      customJson,
    ]
  }
  static func == (lhs: NativeGenerateStreamEvent, rhs: NativeGenerateStreamEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return FoundationModelsApiPigeonInternal.deepEquals(lhs.requestId, rhs.requestId) && FoundationModelsApiPigeonInternal.deepEquals(lhs.parts, rhs.parts) && FoundationModelsApiPigeonInternal.deepEquals(lhs.done, rhs.done) && FoundationModelsApiPigeonInternal.deepEquals(lhs.response, rhs.response) && FoundationModelsApiPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode) && FoundationModelsApiPigeonInternal.deepEquals(lhs.errorMessage, rhs.errorMessage) && FoundationModelsApiPigeonInternal.deepEquals(lhs.customJson, rhs.customJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeGenerateStreamEvent")
    FoundationModelsApiPigeonInternal.deepHash(value: requestId, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: parts, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: done, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: response, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: errorMessage, hasher: &hasher)
    FoundationModelsApiPigeonInternal.deepHash(value: customJson, hasher: &hasher)
  }

  public var description: String {
    return "NativeGenerateStreamEvent(requestId: \(String(describing: requestId)), parts: \(String(describing: parts)), done: \(String(describing: done)), response: \(String(describing: response)), errorCode: \(String(describing: errorCode)), errorMessage: \(String(describing: errorMessage)), customJson: \(String(describing: customJson)))"
  }
}

private class FoundationModelsApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeGenerateRequest.fromList(self.readValue() as! [Any?])
    case 130:
      return NativeMessage.fromList(self.readValue() as! [Any?])
    case 131:
      return NativePart.fromList(self.readValue() as! [Any?])
    case 132:
      return NativeGenerateResponse.fromList(self.readValue() as! [Any?])
    case 133:
      return NativeGenerateStreamEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class FoundationModelsApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeGenerateRequest {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? NativeMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? NativePart {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? NativeGenerateResponse {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? NativeGenerateStreamEvent {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FoundationModelsApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FoundationModelsApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FoundationModelsApiPigeonCodecWriter(data: data)
  }
}

class FoundationModelsApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = FoundationModelsApiPigeonCodec(readerWriter: FoundationModelsApiPigeonCodecReaderWriter())
}

var foundationModelsApiPigeonMethodCodec = FlutterStandardMethodCodec(readerWriter: FoundationModelsApiPigeonCodecReaderWriter());


/// Host API implemented in Swift.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FoundationModelsHostApi {
  /// Generates one final response.
  func generate(request: NativeGenerateRequest, completion: @escaping (Result<NativeGenerateResponse, Error>) -> Void)
  /// Starts a streaming generation and returns its request id.
  func startGenerateStream(request: NativeGenerateRequest, completion: @escaping (Result<String, Error>) -> Void)
  /// Cancels a streaming generation by request id.
  func cancelGenerateStream(requestId: String) throws
  /// Returns whether the native system model is available now.
  func isAvailable(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FoundationModelsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { FoundationModelsApiPigeonCodec.shared }
  /// Sets up an instance of `FoundationModelsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FoundationModelsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Generates one final response.
    let generateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.genkit_foundation_models.FoundationModelsHostApi.generate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! NativeGenerateRequest
        api.generate(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateChannel.setMessageHandler(nil)
    }
    /// Starts a streaming generation and returns its request id.
    let startGenerateStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.genkit_foundation_models.FoundationModelsHostApi.startGenerateStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startGenerateStreamChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! NativeGenerateRequest
        api.startGenerateStream(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startGenerateStreamChannel.setMessageHandler(nil)
    }
    /// Cancels a streaming generation by request id.
    let cancelGenerateStreamChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.genkit_foundation_models.FoundationModelsHostApi.cancelGenerateStream\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelGenerateStreamChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestIdArg = args[0] as! String
        do {
          try api.cancelGenerateStream(requestId: requestIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelGenerateStreamChannel.setMessageHandler(nil)
    }
    /// Returns whether the native system model is available now.
    let isAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.genkit_foundation_models.FoundationModelsHostApi.isAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isAvailableChannel.setMessageHandler { _, reply in
        api.isAvailable { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isAvailableChannel.setMessageHandler(nil)
    }
  }
}

private class PigeonStreamHandler<ReturnType>: NSObject, FlutterStreamHandler {
  private let wrapper: PigeonEventChannelWrapper<ReturnType>
  private var pigeonSink: PigeonEventSink<ReturnType>? = nil

  init(wrapper: PigeonEventChannelWrapper<ReturnType>) {
    self.wrapper = wrapper
  }

  func onListen(withArguments arguments: Any?, eventSink events: @escaping FlutterEventSink)
    -> FlutterError?
  {
    pigeonSink = PigeonEventSink<ReturnType>(events)
    wrapper.onListen(withArguments: arguments, sink: pigeonSink!)
    return nil
  }

  func onCancel(withArguments arguments: Any?) -> FlutterError? {
    pigeonSink = nil
    wrapper.onCancel(withArguments: arguments)
    return nil
  }
}

class PigeonEventChannelWrapper<ReturnType> {
  func onListen(withArguments arguments: Any?, sink: PigeonEventSink<ReturnType>) {}
  func onCancel(withArguments arguments: Any?) {}
}

class PigeonEventSink<ReturnType> {
  private let sink: FlutterEventSink

  init(_ sink: @escaping FlutterEventSink) {
    self.sink = sink
  }

  func success(_ value: ReturnType) {
    sink(value)
  }

  func error(code: String, message: String?, details: Any?) {
    sink(FlutterError(code: code, message: message, details: details))
  }

  func endOfStream() {
    sink(FlutterEndOfEventStream)
  }

}

/// Event-channel API implemented in Swift for streaming events.
class StreamEventsStreamHandler: PigeonEventChannelWrapper<NativeGenerateStreamEvent> {
  static func register(with messenger: FlutterBinaryMessenger,
                      instanceName: String = "",
                      streamHandler: StreamEventsStreamHandler) {
    var channelName = "dev.flutter.pigeon.genkit_foundation_models.FoundationModelsStreamApi.streamEvents"
    if !instanceName.isEmpty {
      channelName += ".\(instanceName)"
    }
    let internalStreamHandler = PigeonStreamHandler<NativeGenerateStreamEvent>(wrapper: streamHandler)
    let channel = FlutterEventChannel(name: channelName, binaryMessenger: messenger, codec: foundationModelsApiPigeonMethodCodec)
    channel.setStreamHandler(internalStreamHandler)
  }
}
      
