// Autogenerated from Pigeon (v27.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed.every(
          ((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]),
        );
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Native generation request sent from Dart to Swift.
class NativeGenerateRequest {
  NativeGenerateRequest({
    required this.messages,
    this.systemInstruction,
    this.configJson,
    this.toolsJson,
  });

  /// Ordered conversation messages to send to the native model.
  List<NativeMessage> messages;

  /// Optional system instruction used to initialize the native session.
  String? systemInstruction;

  /// JSON-encoded generation config such as temperature or token limit.
  String? configJson;

  /// JSON-encoded tool declarations for formatted tool-call prompting.
  String? toolsJson;

  List<Object?> _toList() {
    return <Object?>[messages, systemInstruction, configJson, toolsJson];
  }

  Object encode() {
    return _toList();
  }

  static NativeGenerateRequest decode(Object result) {
    result as List<Object?>;
    return NativeGenerateRequest(
      messages: (result[0]! as List<Object?>).cast<NativeMessage>(),
      systemInstruction: result[1] as String?,
      configJson: result[2] as String?,
      toolsJson: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeGenerateRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(messages, other.messages) &&
        _deepEquals(systemInstruction, other.systemInstruction) &&
        _deepEquals(configJson, other.configJson) &&
        _deepEquals(toolsJson, other.toolsJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeGenerateRequest(messages: $messages, systemInstruction: $systemInstruction, configJson: $configJson, toolsJson: $toolsJson)';
  }
}

/// One conversation message for the native Foundation Models bridge.
class NativeMessage {
  NativeMessage({required this.role, required this.parts});

  /// Genkit role value such as `user`, `model`, or `tool`.
  String role;

  /// Ordered message parts.
  List<NativePart> parts;

  List<Object?> _toList() {
    return <Object?>[role, parts];
  }

  Object encode() {
    return _toList();
  }

  static NativeMessage decode(Object result) {
    result as List<Object?>;
    return NativeMessage(
      role: result[0]! as String,
      parts: (result[1]! as List<Object?>).cast<NativePart>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeMessage || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(role, other.role) && _deepEquals(parts, other.parts);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeMessage(role: $role, parts: $parts)';
  }
}

/// One native message or response part.
class NativePart {
  NativePart({this.text, this.toolRequestJson, this.toolResponseJson});

  /// Plain text content.
  String? text;

  /// JSON-encoded Genkit tool request.
  String? toolRequestJson;

  /// JSON-encoded Genkit tool response.
  String? toolResponseJson;

  List<Object?> _toList() {
    return <Object?>[text, toolRequestJson, toolResponseJson];
  }

  Object encode() {
    return _toList();
  }

  static NativePart decode(Object result) {
    result as List<Object?>;
    return NativePart(
      text: result[0] as String?,
      toolRequestJson: result[1] as String?,
      toolResponseJson: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativePart || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(text, other.text) &&
        _deepEquals(toolRequestJson, other.toolRequestJson) &&
        _deepEquals(toolResponseJson, other.toolResponseJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativePart(text: $text, toolRequestJson: $toolRequestJson, toolResponseJson: $toolResponseJson)';
  }
}

/// Complete native generation response.
class NativeGenerateResponse {
  NativeGenerateResponse({
    required this.parts,
    this.finishReason,
    this.errorCode,
    this.errorMessage,
  });

  /// Response parts returned by the native model bridge.
  List<NativePart> parts;

  /// Optional native finish reason.
  String? finishReason;

  /// Optional native error code.
  String? errorCode;

  /// Optional native error message.
  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[parts, finishReason, errorCode, errorMessage];
  }

  Object encode() {
    return _toList();
  }

  static NativeGenerateResponse decode(Object result) {
    result as List<Object?>;
    return NativeGenerateResponse(
      parts: (result[0]! as List<Object?>).cast<NativePart>(),
      finishReason: result[1] as String?,
      errorCode: result[2] as String?,
      errorMessage: result[3] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeGenerateResponse || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(parts, other.parts) &&
        _deepEquals(finishReason, other.finishReason) &&
        _deepEquals(errorCode, other.errorCode) &&
        _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeGenerateResponse(parts: $parts, finishReason: $finishReason, errorCode: $errorCode, errorMessage: $errorMessage)';
  }
}

/// Event emitted while a native generation request is streaming.
class NativeGenerateStreamEvent {
  NativeGenerateStreamEvent({
    this.requestId,
    this.parts,
    this.done,
    this.response,
    this.errorCode,
    this.errorMessage,
  });

  /// Native stream request id used to filter shared event-channel events.
  String? requestId;

  /// Incremental response parts.
  List<NativePart>? parts;

  /// Whether this event closes the stream.
  bool? done;

  /// Final response included on the closing event.
  NativeGenerateResponse? response;

  /// Optional native stream error code.
  String? errorCode;

  /// Optional native stream error message.
  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[requestId, parts, done, response, errorCode, errorMessage];
  }

  Object encode() {
    return _toList();
  }

  static NativeGenerateStreamEvent decode(Object result) {
    result as List<Object?>;
    return NativeGenerateStreamEvent(
      requestId: result[0] as String?,
      parts: (result[1] as List<Object?>?)?.cast<NativePart>(),
      done: result[2] as bool?,
      response: result[3] as NativeGenerateResponse?,
      errorCode: result[4] as String?,
      errorMessage: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeGenerateStreamEvent ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(requestId, other.requestId) &&
        _deepEquals(parts, other.parts) &&
        _deepEquals(done, other.done) &&
        _deepEquals(response, other.response) &&
        _deepEquals(errorCode, other.errorCode) &&
        _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeGenerateStreamEvent(requestId: $requestId, parts: $parts, done: $done, response: $response, errorCode: $errorCode, errorMessage: $errorMessage)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is NativeGenerateRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is NativeMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is NativePart) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is NativeGenerateResponse) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is NativeGenerateStreamEvent) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NativeGenerateRequest.decode(readValue(buffer)!);
      case 130:
        return NativeMessage.decode(readValue(buffer)!);
      case 131:
        return NativePart.decode(readValue(buffer)!);
      case 132:
        return NativeGenerateResponse.decode(readValue(buffer)!);
      case 133:
        return NativeGenerateStreamEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(
  _PigeonCodec(),
);

/// Host API implemented in Swift.
class FoundationModelsHostApi {
  /// Constructor for [FoundationModelsHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FoundationModelsHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  }) : pigeonVar_binaryMessenger = binaryMessenger,
       pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty
           ? '.$messageChannelSuffix'
           : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Generates one final response.
  Future<NativeGenerateResponse> generate(NativeGenerateRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.genkit_foundation_models.FoundationModelsHostApi.generate$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as NativeGenerateResponse;
  }

  /// Starts a streaming generation and returns its request id.
  Future<String> startGenerateStream(NativeGenerateRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.genkit_foundation_models.FoundationModelsHostApi.startGenerateStream$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[request],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as String;
  }

  /// Cancels a streaming generation by request id.
  Future<void> cancelGenerateStream(String requestId) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.genkit_foundation_models.FoundationModelsHostApi.cancelGenerateStream$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(
      <Object?>[requestId],
    );
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: true,
    );
  }

  /// Returns whether the native system model is available now.
  Future<bool> isAvailable() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.genkit_foundation_models.FoundationModelsHostApi.isAvailable$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}

/// Event-channel API implemented in Swift for streaming events.
Stream<NativeGenerateStreamEvent> streamEvents({String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel streamEventsChannel = EventChannel(
    'dev.flutter.pigeon.genkit_foundation_models.FoundationModelsStreamApi.streamEvents$instanceName',
    pigeonMethodCodec,
  );
  return streamEventsChannel.receiveBroadcastStream().map((dynamic event) {
    return event as NativeGenerateStreamEvent;
  });
}
